"""
Doctor-Ready Summary
-----------------------
Deterministic template, not LLM-generated -- the whole point of this
feature is that it's something the user can trust to accurately reflect
what they actually told the app, not a paraphrase that might drop or
distort something on the way to the clinician.

Explicitly NOT called a medical record anywhere in this module or the
frontend that renders it -- see brief section 11 ("Do not call it a
medical record").
"""

from datetime import datetime, timezone


def _onset_and_severity(answers: list) -> dict:
    onset, severity = None, None
    for a in answers:
        if a["question"].lower().startswith("when did this start"):
            onset = a["answer"]
        if a["question"].lower().startswith("how severe"):
            severity = a["answer"]
    return {"onset": onset, "severity": severity}


def _discussion_questions(matches: list, red_flags: list, triage_category: str) -> list:
    """
    A short, conservative, template-driven list of things worth asking a
    clinician -- generic enough to never overstate what the app knows, but
    specific enough to be genuinely useful to bring to an appointment.
    """
    questions = []
    if red_flags:
        questions.append(
            "I had some symptoms flagged as urgent by a symptom-checker app ("
            + ", ".join(red_flags) + ") -- should these be evaluated today?"
        )
    if triage_category in ("URGENT_MEDICAL_EVALUATION",):
        questions.append("Given my symptoms, how soon should I be seen?")
    for m in matches[:3]:
        questions.append(f"Could my symptoms be related to {m.name.lower()}, or something else entirely?")
    if not matches:
        questions.append("My symptoms didn't clearly match a common pattern -- what should I watch for?")
    questions.append("Are there any tests that would help clarify what's going on?")
    return questions


def build_summary(
    raw_text: str,
    extracted_symptoms: list,
    answers: list,
    matches: list,
    red_flags: list,
    triage_category: str,
    triage_label: str,
) -> dict:
    """
    answers: output of questions.question_engine.answers_summary()
    matches: list of ConditionMatch
    """
    onset_severity = _onset_and_severity(answers)
    associated = [a for a in answers if a["question"] not in (
        "When did this start?", "How severe would you say it is right now?"
    )]

    structured = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "main_symptoms": extracted_symptoms,
        "onset": onset_severity["onset"] or "Not specified",
        "severity": onset_severity["severity"] or "Not specified",
        "duration": onset_severity["onset"] or "Not specified",
        "associated_symptoms_and_answers": associated,
        "red_flags_noted": red_flags,
        "triage_category": triage_category,
        "triage_label": triage_label,
        "possible_explanations_considered": [
            {"name": m.name, "matched_symptoms": m.matched_symptoms, "severity": m.severity}
            for m in matches
        ],
        "questions_to_discuss_with_clinician": _discussion_questions(matches, red_flags, triage_category),
        "original_description": raw_text,
        "not_a_medical_record_notice": (
            "This is a self-reported summary generated by an informational app, not a "
            "medical record and not a diagnosis. Bring it to your appointment as a starting "
            "point for discussion."
        ),
    }
    structured["plain_text"] = _render_plain_text(structured)
    return structured


def _render_plain_text(s: dict) -> str:
    lines = [
        "SYMPTOM SUMMARY (self-reported, not a medical record)",
        f"Generated: {s['generated_at_utc']}",
        "",
        f"Main symptoms: {', '.join(s['main_symptoms']) if s['main_symptoms'] else 'Not specified'}",
        f"Onset: {s['onset']}",
        f"Severity: {s['severity']}",
        "",
        "Answers given during the symptom check:",
    ]
    if s["associated_symptoms_and_answers"]:
        for qa in s["associated_symptoms_and_answers"]:
            lines.append(f"  - {qa['question']} -> {qa['answer']}")
    else:
        lines.append("  (none recorded)")

    if s["red_flags_noted"]:
        lines.append("")
        lines.append(f"Red flags noted by the app's safety check: {', '.join(s['red_flags_noted'])}")

    lines.append("")
    lines.append(f"App's triage suggestion: {s['triage_label']}")

    lines.append("")
    lines.append("Possible explanations considered by the app (not a diagnosis):")
    if s["possible_explanations_considered"]:
        for m in s["possible_explanations_considered"]:
            lines.append(f"  - {m['name']} (severity: {m['severity']}; matched on: {', '.join(m['matched_symptoms'])})")
    else:
        lines.append("  (no confident match found)")

    lines.append("")
    lines.append("Questions to discuss with your clinician:")
    for q in s["questions_to_discuss_with_clinician"]:
        lines.append(f"  - {q}")

    lines.append("")
    lines.append(f"Original description given: \"{s['original_description']}\"")
    lines.append("")
    lines.append(s["not_a_medical_record_notice"])
    return "\n".join(lines)
